import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Github,Linkedin,Mail} from "lucide-react";
import Navigation from "@/components/Navigation";import Footer from "@/components/Footer";
import {DotGrid,OutlineSquares,ProjectCard,SectionTitle,SkillBlock} from "@/components/PortfolioUI";
import {getProjects,type Project} from "@/lib/api";
const Index=()=>{const[projects,setProjects]=useState<Project[]>([]);useEffect(()=>{const c=new AbortController();getProjects(c.signal).then(setProjects).catch(()=>undefined);return()=>c.abort()},[]);return <div className="min-h-screen"><Navigation/><main id="main-content">
<section id="home" className="portfolio-shell grid min-h-[570px] items-center gap-12 py-16 md:grid-cols-2"><div><h1 className="text-[32px] font-semibold leading-[1.35]">Ibrahim est <span className="text-primary">développeur Full Stack</span> et <span className="text-primary">ingénieur logiciel</span></h1><p className="mt-8 leading-relaxed text-muted-foreground">Je conçois des applications web, mobiles et backend fiables, accessibles et centrées sur l’utilisateur.</p><a href="#contacts" className="portfolio-button mt-6">Me contacter&nbsp;!!</a></div><div className="relative mx-auto w-full max-w-[460px]"><OutlineSquares className="absolute left-2 top-20 -z-0"/><DotGrid className="absolute bottom-20 right-0"/><img src={`${import.meta.env.BASE_URL}image 1.png`} alt="Ibrahim Rahmani" className="relative z-10 mx-auto h-[380px] w-auto object-contain object-bottom"/><div className="relative z-20 flex items-center gap-3 border border-muted-foreground bg-background p-2 text-sm"><span className="h-4 w-4 bg-primary"/>Disponible pour de nouveaux projets</div></div></section>
<section className="portfolio-shell py-14"><blockquote className="mx-auto max-w-[710px] border border-muted-foreground p-8 text-center text-2xl font-medium">“La qualité du code transforme une idée en produit durable.”<footer className="mt-5 text-right text-base text-muted-foreground">— Ibrahim Rahmani</footer></blockquote></section>
<section className="portfolio-shell py-20"><div className="flex items-center justify-between"><SectionTitle>projects</SectionTitle><Link to="/projects" className="shrink-0 text-sm">Tout voir ~~&gt;</Link></div>{projects.length?<div className="mt-12 grid gap-4 md:grid-cols-3">{projects.slice(0,3).map(p=><ProjectCard key={p.id} project={p}/>)}</div>:<p className="mt-12 text-muted-foreground">Chargement des projets…</p>}</section>
<section className="portfolio-shell grid gap-12 py-20 md:grid-cols-[1fr_2fr]"><div><SectionTitle>skills</SectionTitle><div className="relative mt-16 h-64"><DotGrid/><OutlineSquares className="absolute bottom-0 right-10"/></div></div><div className="grid content-center gap-4 sm:grid-cols-3"><SkillBlock title="Languages" items={["TypeScript","JavaScript","Python","Java","C++"]}/><SkillBlock title="Databases" items={["PostgreSQL","MySQL","SQLite"]}/><SkillBlock title="Tools" items={["Git","Docker","Linux","Figma"]}/><SkillBlock title="Frameworks" items={["React","Django","Spring Boot","Tailwind"]}/><SkillBlock title="Other" items={["REST","CI/CD","Accessibility","SEO"]}/></div></section>
<section className="portfolio-shell py-20"><SectionTitle>about-me</SectionTitle><div className="mt-10 grid items-center gap-14 md:grid-cols-2"><div className="space-y-6 leading-relaxed text-muted-foreground"><p>Bonjour, je suis Ibrahim !</p><p>Développeur Full Stack passionné par la création de produits numériques utiles, je transforme les besoins métier en interfaces claires et en architectures robustes.</p><p>Je travaille avec React, Django, Java et les technologies cloud, en accordant une attention particulière à la qualité, l’accessibilité et l’expérience utilisateur.</p><Link to="/about" className="portfolio-button">En savoir plus -&gt;</Link></div><div className="relative mx-auto"><DotGrid className="absolute -left-8 top-14"/><img src={`${import.meta.env.BASE_URL}image 1.png`} alt="Portrait d’Ibrahim Rahmani" className="relative h-[430px] w-auto object-contain"/></div></div></section>
<section id="contacts" className="portfolio-shell py-20"><SectionTitle>contacts</SectionTitle><div className="mt-10 grid gap-12 md:grid-cols-2"><p className="leading-relaxed text-muted-foreground">Vous avez un projet, une opportunité ou souhaitez simplement échanger ? Écrivez-moi, je répondrai rapidement.</p><div className="justify-self-start border border-muted-foreground p-4 md:justify-self-end"><h3 className="mb-4 font-semibold">Contactez-moi ici</h3><div className="space-y-3 text-muted-foreground"><a className="flex gap-2 hover:text-white" href="mailto:rahmaniibrahim042@gmail.com"><Mail/>Email</a><a className="flex gap-2 hover:text-white" href="https://github.com/ibrahimrahmani555"><Github/>GitHub</a><a className="flex gap-2 hover:text-white" href="https://www.linkedin.com/in/ibrahim-rahmani-433418387/"><Linkedin/>LinkedIn</a></div></div></div></section>
</main><Footer/></div>};export default Index;
