import {useEffect,useState} from "react";import {ArrowDown,ArrowUpRight,Check} from "lucide-react";import {Link} from "react-router-dom";import Navigation from "@/components/Navigation";import Footer from "@/components/Footer";import {ProjectTile,ServiceCard} from "@/components/ArikUI";import {getProjects,type Project} from "@/lib/api";
const process=[{"tag":"Découverte","title":"Analyse du besoin","text":"Nous clarifions vos objectifs, vos utilisateurs et les problèmes que le produit doit résoudre."},{"tag":"Stratégie","title":"Conception & architecture","text":"Je transforme les besoins en parcours, maquettes et architecture technique cohérente."},{"tag":"Création","title":"Design d’interface","text":"Je construis une interface haut de gamme, accessible et fidèle à votre identité."},{"tag":"Développement","title":"Implémentation","text":"React, Django ou Spring Boot donnent vie au produit avec une base maintenable."},{"tag":"Qualité","title":"Tests & déploiement","text":"Tests, CI/CD, performance, SEO et suivi garantissent une mise en production fiable."}];
const Index=()=>{const[projects,setProjects]=useState<Project[]>([]);useEffect(()=>{const c=new AbortController();getProjects(c.signal).then(setProjects).catch(()=>undefined);return()=>c.abort()},[]);return <div id="top" className="min-h-screen"><Navigation/><main id="main-content">
<section className="relative flex min-h-[1080px] flex-col items-center justify-end overflow-hidden px-6 pb-24 pt-36 text-center"><div className="absolute top-5 h-[760px] w-[min(880px,92vw)] overflow-hidden mix-blend-lighten"><div className="absolute inset-0 z-10 bg-gradient-to-b from-transparent via-transparent to-background"/><img src={`${import.meta.env.BASE_URL}ibrahim-arik-portrait.png`} alt="Portrait cinématique d’Ibrahim Rahmani" fetchPriority="high" className="mx-auto h-full w-full object-cover object-[center_22%] contrast-110"/></div><div className="relative z-10 max-w-[1050px]"><h1 className="text-[clamp(64px,9vw,150px)] font-light leading-[.86] tracking-[-.05em]">Full Stack Developer<br/><span className="arik-italic">& Software Engineer</span></h1><p className="mx-auto mt-8 max-w-xl text-lg leading-8 text-primary/55">Développement web, mobile, backend et DevOps pour créer des produits numériques utiles, rapides et durables.</p><a href="#services" className="mt-12 inline-flex items-center gap-4 text-xs uppercase tracking-widest"><span className="arik-circle"><ArrowDown size={15}/></span>Mes services</a></div></section>
<div className="arik-shell grid grid-cols-2 gap-8 py-14 text-center text-sm uppercase tracking-[.2em] text-primary/45 md:grid-cols-6"><span>React</span><span>Django</span><span>Spring</span><span>TypeScript</span><span>Docker</span><span>PostgreSQL</span></div>
<section id="services" className="arik-shell grid gap-5 py-20 md:grid-cols-3"><ServiceCard index="01" title="Frontend">Interfaces React modernes, responsives et accessibles, pensées pour une expérience fluide.</ServiceCard><ServiceCard index="02" title="Backend">API robustes avec Django REST et Spring Boot, sécurité, rôles et données PostgreSQL.</ServiceCard><ServiceCard index="03" title="DevOps & SEO">CI/CD, déploiement cloud, performance, observabilité et optimisation du référencement.</ServiceCard></section>
<section className="arik-shell py-28"><div className="mb-14 flex items-end justify-between"><h2 className="text-5xl md:text-7xl">Projets sélectionnés</h2><Link to="/projects" className="flex items-center gap-3 text-xs uppercase tracking-widest"><span className="arik-circle"><ArrowUpRight size={15}/></span>Tout voir</Link></div>{projects.length?<div className="grid gap-6 md:grid-cols-2">{projects.slice(0,4).map(p=><ProjectTile key={p.id} project={p}/>)}</div>:<p className="arik-panel p-10 text-primary/55">Chargement des projets depuis l’API…</p>}</section>
<section className="py-28 text-center"><p className="arik-label">Le processus</p><h2 className="mx-auto mt-5 max-w-4xl text-6xl leading-none md:text-[110px]">Votre produit en <span className="arik-italic">5 étapes</span></h2><p className="mx-auto mt-8 max-w-lg leading-7 text-primary/55">Une démarche structurée transforme votre idée en solution fonctionnelle et maintenable.</p></section>
<section className="arik-shell relative mx-auto max-w-[1080px] pb-32"><div className="absolute bottom-0 left-1/2 top-0 hidden w-px bg-primary/15 md:block"/>{process.map((s,i)=><article key={s.title} className={`relative mb-[-30px] grid md:grid-cols-2 ${i%2?"":"md:text-right"}`}><div className={`${i%2?"md:col-start-2 md:pl-20":"md:pr-20"}`}><div className="arik-panel p-10"><span className="arik-label">{s.tag}</span><h3 className="mt-2 text-2xl uppercase tracking-wide">{s.title}</h3><p className="mt-5 leading-7 text-primary/55">{s.text}</p><p className="mt-6 flex items-center gap-3 text-sm"><Check size={14}/>Livrable validé</p></div></div><span className="arik-circle absolute left-1/2 top-1/2 hidden -translate-x-1/2 -translate-y-1/2 text-xs md:flex">0{i+1}</span></article>)}</section>
<section id="contact" className="border-y border-primary/15 bg-primary/[.045] px-6 py-32 text-center"><p className="arik-label">Un projet en tête ?</p><h2 className="mx-auto mt-5 max-w-5xl text-6xl leading-none md:text-[116px]">Créons un produit<br/><span className="arik-italic">qui se démarque</span></h2><p className="mx-auto mt-8 max-w-lg leading-7 text-primary/55">Parlons de votre idée et construisons une solution claire, fiable et performante.</p><a href="mailto:rahmaniibrahim042@gmail.com" className="arik-button mt-8">Me contacter <ArrowUpRight size={16}/></a></section>
</main><Footer/></div>};export default Index;
